export const API_ENDPOINT = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  REGISTER: "/auth/register",
  LOGIN_WITH_GOOGLE: "/auth/google-link",
  FORGOT_PASSWORD: "/auth/forgot-password",
  SEND_OTP: "/auth/otp",
  PROFILE: "/profile",
  UPLOAD: "/media/images/upload/presigned-url",
  UPDATE_PROFILE: "/profile",
  SETUP_2FA: "/auth/2fa/setup",
  ENABLE_2FA: "/auth/2fa/enable",
  DISABLE_2FA: "/auth/2fa/disable",
  CHANGE_PASSWORD: "/profile/change-password",
  GET_ALL_USERS: "/users",
  CREATE_USER: "/users",
  UPDATE_USER: "/users",
  GET_ALL_ROLES: "/roles",
  GET_ALL_PERMISSIONS: "/permissions",
  COURSES: "/courses",
  CHAPTERS: "/chapters",
  LESSONS: "/lessons",
} as const;
